---
version: 0.2

env:
  variables:
    SOURCE_NAME: ojosama.zip
    FUNCTION_NAME: ojosama
    GOARCH: amd64
    GOOS: linux

phases:
  install:
    runtime-versions:
      golang: 1.18

    commands:
      - cd ojosama-api
      - go mod download

  pre_build:
    commands:
      - go vet .
      - go test -cover ./...

  build:
    commands:
      - go build -tags lambda.norpc -o bootstrap
      - zip "${SOURCE_NAME}" bootstrap
      - mv "${SOURCE_NAME}"  ../
      - cd ../

  post_build:
    commands:
      - cd ojosama-assets
      - aws s3 cp ./ "s3://${S3_BUCKET_ASSETS}/" --recursive
      - cd ../

      - aws s3 cp "./${SOURCE_NAME}" "s3://${S3_BUCKET_LAMBDA}/"
      - aws lambda update-function-code --function-name "${FUNCTION_NAME}" --s3-bucket "${S3_BUCKET_LAMBDA}" --s3-key "${SOURCE_NAME}"
