---
version: 0.2

env:
  variables:
    HANDLER: main
    SOURCE_NAME: ojosama.zip

phases:
  install:
    runtime-versions:
      golang: 1.18

    commands:
      - cd ojosama-api
      - go mod download

  pre_build:
    commands:
      - go vet .
      - go test -cover ./...

  build:
    commands:
      - go build -o "${HANDLER}"
      - zip "${SOURCE_NAME}" "${HANDLER}"
      - mv "${SOURCE_NAME}"  ../
      - cd ../

  post_build:
    commands:
      # FIXME: 一時的なパスなので命名が適当ではない
      - cd docs/swagger/
      - aws s3 cp ./ "s3://${S3_BUCKET_ASSETS}/" --recursive
      - cd ../../

      - aws s3 cp "./${SOURCE_NAME}" "s3://${S3_BUCKET_LAMBDA}/"
      - aws lambda update-function-code --function-name ojosama --s3-bucket "${S3_BUCKET_LAMBDA}" --s3-key "${SOURCE_NAME}"
