---

name: test

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README*
      - docs/*
      - ojosama-assets/*
      - buildspec.yml
  pull_request:
    paths-ignore:
      - README*
      - docs/*
      - ojosama-assets/*
      - buildspec.yml

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.18'
          - '1.19'
          - '1.x'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: make -C ojosama-api
