---

name: test

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README*
      - LICENSE
      - docs/*
  pull_request:
    paths-ignore:
      - README*
      - LICENSE
      - docs/*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.18'
          - '1.x'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go build
      - run: go install
      - run: go test -cover ./...
      - run: make -C ojosama-api

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build .
